### PR TITLE
First Version of Node Documentation

### PR DESCRIPTION
**Pull request by bmuenzenmeyer**
Per https://github.com/pattern-lab/patternlab-node/issues/70 I've finished the first rev of documentation for patternlab node. It's been a good exercise, as I've come to realize there are still some basic gaps in functionality that will be ported in the short to mid term.

@dmolsen and @bradfrost if you could look over these changes I would appreciate it. 

Of specific note is an additional section in the `docs/index.html`
image

...and a docs/node/detail.html page
image

Node has it's own nav, but I've chosen to link to existing PHP documentation where they are identical.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@dmolsen @bradfrost it also seems as if the dev branch is not aligned with master. should this PR target master directly?

**Comment by dmolsen** [comment]
I'm merging this with `dev` but let's leave it there for a little. I want to stick to `dev` because PL in general follows the git flow model. `master` should only be for full releases.

@bradfrost -

I'm really not a fan of the IA with the docs and ports. Can you come up with a  new organization for how you'd like to see these things organized, please? This is feeling a little hacked and we need a more robust solution. Please branch off of `dev` with a  feature branch if you have to play around a lot.

**Comment by bradfrost** [comment]
Yeah I agree we'll need a more robust and sensible architecture for the docs. I'm going to be traveling for the next month so I won't be able to execute on it, but I can definitely play. I think something like tabs (similar to [MediaTemple's docs](https://kb.mediatemple.net/questions/61/How+can+I+test+or+preview+my+website+before+switching+DNS%3F#gs)), or an accordion style might work.

**Comment by bmuenzenmeyer** [comment]
@dmolsen have you considered what the IA for documentation will be for PL 2.0? I want to put some more work into PL NODE and am currently leaning toward a github wiki as a middle step until this is figured out. thoughts?

**Comment by bradfrost** [comment]
@bmuenzenmeyer this is still in the works, and I still think my previous comment about keeping everything under one roof using tabs would be an effective way to keep everything together.

**Comment by bmuenzenmeyer** [comment]
I can take a stab at making this tabular - no ETA on it however.
Wish me luck ! :rocket:

**Pull request merged**
